
import { StyleSheet } from 'react-native';

export const colors = {
  primary: '#00F0A0',
  secondary: '#9C27B0',
  backgroundLight: '#f6f7f8',
  backgroundDark: '#0D0C1D',
  surfaceDark: '#16152C',
  textLight: '#f6f7f8',
  textDark: '#0D0C1D',
  slate100: '#f1f5f9',
  slate200: '#E2E8F0',
  slate400: '#94A3B8',
  slate800: '#1e293b',
  red400: '#F87171',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.backgroundDark,
    color: colors.slate100,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    paddingBottom: 8,
    backgroundColor: colors.backgroundDark,
  },
  headerTitle: {
    color: colors.slate100,
    fontSize: 30,
    fontWeight: 'bold',
  },
  searchButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.surfaceDark,
    justifyContent: 'center',
    alignItems: 'center',
  },
  main: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  subscriptionItem: {
    flexDirection: 'column',
    gap: 16,
    borderRadius: 16,
    backgroundColor: colors.surfaceDark,
    padding: 16,
    marginBottom: 12,
  },
  itemRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 16,
  },
  itemFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  subscriptionIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  subscriptionInfo: {
    flex: 1,
  },
  subscriptionName: {
    fontSize: 16,
    fontWeight: '600',
    color: 'white',
  },
  subscriptionNextPayment: {
    fontSize: 14,
    color: colors.slate400,
  },
  subscriptionAmount: {
    fontSize: 18,
    fontWeight: 'bold',
    color: 'white',
  },
  paymentStatusText: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.primary,
  },
  paidStatusText: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.slate400,
  },
  deleteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    borderRadius: 9999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  deleteButtonText: {
    color: colors.red400,
    fontSize: 12,
    fontWeight: '600',
  },
  updateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(37, 205, 25, 0.1)',
    borderRadius: 9999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  updateButtonText: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '600',
  },
  footer: {
    padding: 16,
    backgroundColor: 'rgba(13, 12, 29, 0.8)',
    borderTopWidth: 1,
    borderColor: colors.slate800,
  },
  addButton: {
    height: 56,
    borderRadius: 12,
    backgroundColor: colors.primary,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  addButtonText: {
    color: colors.backgroundDark,
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
  },
  modalView: {
    width: '90%',
    maxWidth: 360,
    backgroundColor: colors.surfaceDark,
    borderRadius: 12,
    padding: 24,
    gap: 24,
  },
  modalText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: 'white',
    textAlign: 'center',
  },
  datePickerContainer: {
    gap: 8,
  },
  datePickerLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.slate400,
  },
  datePickerInputContainer: {
    height: 48,
    justifyContent: 'center',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.slate800,
    backgroundColor: colors.backgroundDark,
    paddingHorizontal: 16,
  },
  datePickerInput: {
    fontSize: 16,
    color: colors.slate100,
  },
  modalButtonContainer: {
    flexDirection: 'row',
    gap: 16,
  },
  modalButton: {
    flex: 1,
    height: 48,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  confirmButton: {
    backgroundColor: colors.primary,
    shadowColor: colors.primary,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  cancelButton: {
    backgroundColor: 'rgba(51, 65, 85, 0.5)',
  },
  confirmButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.backgroundDark,
  },
  cancelButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.slate200,
  },
});
